Category.create([
  {categoname: "WS学内"},
  {categoname: "WS学外"},
  {categoname: "教育パッケージ"},
  {categoname: "ボードゲーム製作"},
  {categoname: "白山都市計画"},
  {categoname: "tech"},
  {categoname: "ラジオ"},
  {categoname: "ジーザ-育成"},
  {categoname: "キャンプ"},
  {categoname: "イベント企画"},
  {categoname: "勉強会"},
  {categoname: "&nbsp;"},
  {categoname: "エシカル商品"},
  {categoname: "ニュース"},
  {categoname: "書籍"},
  {categoname: "英語"},
  {categoname: "動画制作"},
  {categoname: "アプリ"},
  {categoname: "web製作"},
  {categoname: "ポスター"},

])